apiVersion: v1
kind: Secret
metadata:
  name: rds-db-secrets
type: Opaque
stringData:
  DB_USERNAME: "dbadmin"
  DB_PASSWORD: "smith1234"
  DB_HOST: "terraform-20260612074353910200000004.c0de0qocu6j6.us-east-1.rds.amazonaws.com"
  DB_NAME: "appdb"